---
- name: Install zsh
  dnf: name=zsh state=latest
  become: yes
  register: shell_install

- name: Clone oh-my-zsh
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    accept_hostkey: true
    force: no
    update: yes
  when: shell_install|succeeded
  register: clone

- name: Copy default .zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    force: no
  when: clone|succeeded
  register: copy

- name: Set zsh as default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh
  when: copy|succeeded
  become: yes

- name: Install variables
  copy:
    src: variables.zsh
    dest: ~/.oh-my-zsh/custom/variables.zsh

- name: Install aliases
  copy:
    src: aliases.zsh
    dest: ~/.oh-my-zsh/custom/aliases.zsh
