---
- name: restart_docker
  systemd:
    name: docker
    state: restarted
  become: yes

- name: install_docker_compose
  copy:
    src: /tmp/docker-compose
    dest: /usr/local/bin/docker-compose
    mode: "u+x,g+x,o+x"
  become: yes
