---
- name: Add official repositories
  yum_repository:
    name: docker
    description: Official docker repository
    baseurl: https://docs.docker.com/engine/installation/linux/repo_files/fedora/docker.repo
  become: yes

- name: Install docker
  dnf: name=docker-engine state=latest
  become: yes

- name: Start docker
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Create docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  notify: restart_docker
  become: yes

- name: Detect docker-compose binary
  stat: path=/usr/local/bin/docker-compose
  register: docker_compose_binary

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.11.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /tmp/docker-compose
  when: not docker_compose_binary.stat.exists
  notify: install_docker_compose
